all:
	mkdir -p bin
	clang++-7 -pthread -o bin/main main.cpp

simples:
	mkdir -p bin
	clang++-7 -pthread -o bin/simples main_simples.cpp

vetor:
	mkdir -p bin
	clang++-7 -pthread -o bin/vetor main_vetor.cpp
